apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  labels:
    app: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-demo
  template:
    metadata:
      labels:
        app: otel-demo
    spec:
      containers:
      - name: otel-demo
        image: omegazyadav/note-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_DSN
          value: "host=postgres user=user password=password dbname=notesdb port=5432 sslmode=disable"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=otel-demo"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "always_on"
        - name: LOKI_URL
          value: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
---

apiVersion: v1
kind: Service
metadata:
  name: otel-demo
spec:
  selector:
    app: otel-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


