apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.default.svc.cluster.local:3100
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
        isDefault: false
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoria-metrics.default.svc.cluster.local:8428
        isDefault: false
        jsonData:
          httpMethod: POST
          prometheusType: VictoriaMetrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [auth.anonymous]
    # Enable anonymous access
    enabled = true
    # Specify organization name that should be used for unauthenticated users
    org_name = Main Org.
    # Specify role for unauthenticated users
    org_role = Admin
    
    [auth]
    # Optionally hide the login form completely
    disable_login_form = true
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config
              mountPath: /etc/grafana
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-config
          configMap:
            name: grafana-config
