apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-demo'
              scrape_interval: 5s
              static_configs:
                - targets: ['otel-demo:8080']

            - job_name: 'argo-server'
              scrape_interval: 15s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              static_configs:
                - targets: ['argo-server.argo.svc.cluster.local:2746']

            - job_name: 'argo-workflow-controller'
              scrape_interval: 15s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              static_configs:
                - targets: ['workflow-controller-metrics.argo.svc.cluster.local:9090']

    processors:
      filter/drop_unwanted:
        error_mode: ignore
        metrics:
          metric:
            - 'IsMatch(name, "^grpc_.*")'
            - 'IsMatch(name, "^gc_.*")'
            - 'IsMatch(name, "^go_.*")'

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8081"
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [prometheus, otlp]
          processors: [filter/drop_unwanted]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [debug]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          ports:
            - containerPort: 8081 # prometheus
          args:
            - "--config=/etc/otel-collector-config.yaml"
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: prome-exporter
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

