apiVersion: v1
kind: Secret
metadata:
  name: otel-db-secrets
type: Opaque
stringData:
  DB_PASSWORD: "password"
  DB_DSN: "host=postgres user=user password=password dbname=notesdb port=5432 sslmode=disable"
