fullnameOverride: otel-collector

mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector
  tag: latest

ports:
  prom-exporter:
    enabled: true
    containerPort: 8081
    servicePort: 8081
    protocol: TCP

service:
  type: ClusterIP

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-demo'
            scrape_interval: 5s
            static_configs:
              - targets: ['otel-demo:8080']
          - job_name: 'argo-server'
            scrape_interval: 15s
            scheme: https
            tls_config:
              insecure_skip_verify: true
            static_configs:
              - targets: ['argo-server.argo.svc.cluster.local:2746']
          - job_name: 'argo-workflow-controller'
            scrape_interval: 15s
            scheme: https
            tls_config:
              insecure_skip_verify: true
            static_configs:
              - targets: ['workflow-controller-metrics.argo.svc.cluster.local:9090']

  processors:
    filter/drop_unwanted:
      error_mode: ignore
      metrics:
        metric:
          - 'IsMatch(name, "^grpc_.*")'
          - 'IsMatch(name, "^gc_.*")'
          - 'IsMatch(name, "^go_.*")'

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8081"
    debug:
      verbosity: detailed

  service:
    pipelines:
      metrics:
        receivers: [prometheus, otlp]
        processors: [filter/drop_unwanted]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        exporters: [debug]
